
logging:
  level:
    '[org.springframework.web]': debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?serverTimezone=Asia/Seoul&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: thd123

mybatis:
    type-aliases-package: co.primeblock
    mapper-locations:
    - classpath:/mapper/**/*.xml